---
fail_fast: true
default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.2.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pylint
    rev: "v2.13.5"
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
      - id: mypy
        additional_dependencies:
          - attrs
          - types-pyyaml
        args: []
  - repo: https://github.com/snakemake/snakefmt
    rev: "v0.6.0"
    hooks:
      - id: snakefmt
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.26.3"
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible-community/ansible-lint
    rev: "v6.0.2"
    hooks:
      - id: ansible-lint
  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.14.3"
    hooks:
      - id: check-github-workflows
