---
fail_fast: true
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        # TODO switch to lf
        args: [--fix, "no"]
      # - id: no-commit-to-branch
      #   args: [--branch, main, --branch, master, --branch, devel]
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
  # - repo: https://github.com/PyCQA/flake8
  #   rev: "6.0.0"
  #   hooks:
  #     - id: flake8
  # - repo: https://github.com/PyCQA/pylint
  #   rev: "v3.0.0a6"
  #   hooks:
  #     - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        additional_dependencies:
          - attrs
          - types-pyyaml
        args: []
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.32.0"
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible-community/ansible-lint
    rev: "v6.18.0"
    hooks:
      - id: ansible-lint
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.26.3"
    hooks:
      - id: check-github-workflows
