[tool.setuptools]
include-package-data = false
zip-safe = false

[tool.setuptools.packages.find]
namespaces = false
where = ["."]

[tool.setuptools.package-data]
REPONAME = [
    "py.typed"
]

[tool.isort]
profile = "black"
# default is FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
# Placing third-party imports at the end makes their inclusion more obvious
sections = ["FUTURE", "STDLIB", "ATTRS", "FIRSTPARTY", "THIRDPARTY", "LOCALFOLDER"]
known_attrs = ["attr"]

[tool.ruff]
line-length = 100

[tool.ruff.format]
skip-magic-trailing-comma = true

# For disabling all fixes/lints.
# [tool.ruff.lint]
# select = []

[tool.ruff.lint.isort]
lines-after-imports = 2
section-order = ["future", "standard-library", "first-party", "third-party", "local-folder"]

# ???
# [tool.ruff.per-file-ignores]
# "test/test*.py" = [
#     "PLR2004", # magic value comparison
#     "S101",    # use of assert detected
#     "TCH002",  # third party import (for pytest)
# ]

[tool.mypy]
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true

scripts_are_modules = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
    "psi4",
    "pyscf",
]
ignore_missing_imports = true

[tool.towncrier]
    package="REPONAME"
    filename="CHANGELOG.md"
    issue_format = "`#{issue} <https://github.com/berquist/REPONAME/issues/{issue}>`_"

    [[tool.towncrier.type]]
        directory = "breaking"
        name = "Backward-incompatible Changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "deprecation"
        name = "Deprecations"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "feature"
        name = "New Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bug Fixes"
        showcontent = true
